var render = function render(){var _vm=this,_c=_vm._self._c;return _c('div',[_c('BaseCleanPopup',{directives:[{name:"body",rawName:"v-body"},{name:"zindex",rawName:"v-zindex"}],ref:"popup",attrs:{"h":40,"w":300,"winh":446,"winw":317},on:{"close":_vm.closeExplorer},scopedSlots:_vm._u([{key:"header",fn:function(){return [_c('div',{staticClass:"title"},[_vm._v("\n        "+_vm._s(_vm.$t("general.select"))+"\n        "+_vm._s(_vm.showfiles ? _vm.$t("files1.file") : _vm.$t("files1.place"))+"\n      ")])]},proxy:true}])},[_c('div',{directives:[{name:"remove",rawName:"v-remove.offline",modifiers:{"offline":true}}],staticClass:"absolute h-100 w-100 text-a-center"},[_c('h1',{staticClass:"unauthorized"},[_vm._v(_vm._s(_vm.$t("general.notAllow")))])]),_c('div',{directives:[{name:"remove",rawName:"v-remove.online",modifiers:{"online":true}}],staticClass:"h-100"},[_c('div',{staticClass:"outer-list flex-align-center",staticStyle:{"height":"calc(100% - 90px)"}},[_c('div',{staticClass:"content h-100"},[_c('div',{staticClass:"header dir-rtl rtl flex padd-6 border-b-light padd-l-12"},[_c('div',{staticClass:"home icon-item rtl icon-otzar otz-icon-square otz-icon border-l-light",on:{"click":_vm.loadHome}},[_vm._v("\n              o\n            ")]),_c('div',{directives:[{name:"tooltip",rawName:"v-tooltip",value:({
                content: _vm.$t('general.back'),
              }),expression:"{\n                content: $t('general.back'),\n              }"}],staticClass:"back icon-otzar otz-icon-square otz-icon",staticStyle:{"transform":"rotate(90deg)"},on:{"click":_vm.goUp}},[_vm._v("\n              2\n            ")]),_c('div',{staticClass:"flex-g-1 mrg-r-6",attrs:{"dir":"ltr"}},[_c('input',{staticClass:"w-100 padd-3",attrs:{"type":"text","disabled":""},domProps:{"value":_vm.curPath}})])]),_c('contentExplore',{attrs:{"list":_vm.folders,"files":_vm.files,"showfiles":_vm.showfiles,"active":_vm.active},on:{"open":_vm.openFold,"select":_vm.selectFold}})],1)]),_c('div',{staticClass:"dir-rtl rtl border-t-light flex flex-align-center padd-6 padd-l-12"},[_vm._v("\n        "+_vm._s(_vm.showfiles ? _vm.$t("files1.selectFile") : _vm.$t("files1.selectFolder"))+":\n         \n        "),_c('input',{staticClass:"flex-g-1",staticStyle:{"direction":"ltr"},attrs:{"disabled":"","type":"text"},domProps:{"value":this.active.dir
              ? _vm.calcPath(this.active)
              : _vm.showfiles
              ? _vm.noSelectedFile
              : _vm.noSelectedFolder}})]),_c('div',{staticClass:"footer border-t-light padd-12"},[_c('div',{staticClass:"flex-g-1 rtl flex-center"},[_c('div',{staticClass:"flex-center"},[_c('BaseButton',{on:{"click":_vm.selectAndClose}},[_vm._v(_vm._s(_vm.$t("general.select")))])],1),_c('div',{staticClass:"flex-center"},[_c('BaseButton',{on:{"click":_vm.closeExplorer}},[_vm._v(_vm._s(_vm.$t("general.cancel")))])],1)])])])])],1)
}
var staticRenderFns = []

export { render, staticRenderFns }