var render = function render(){var _vm=this,_c=_vm._self._c;return _c('div',{staticClass:"contact-main-block w-100 relative"},[_c('HeaderMenu',{class:{ 'mrg-b-30': !_vm.$store.state.hasInternet },attrs:{"title":_vm.$_mobile ? _vm.$t('general.hello') + ' ' + _vm.getUserName : _vm.title,"routeBackName":_vm.$_mobile ? '' : _vm.routeBackName}}),_c('div',[_c('div',{staticClass:"contact-support-team"},[_c('div',{staticClass:"contact-support",staticStyle:{"padding-top":"0px"}},[_c('div',{staticClass:"mrg-b-6 bold main-title"},[_vm._v("\n          "+_vm._s(this.$t("myLicense.OH_license"))+"\n          "),(_vm.mainEditionDesc != '' && !this.hasOtzarConnection)?_c('div',{staticClass:"not-connected"},[_vm._v("\n            ("+_vm._s(_vm.$t("login.notConnectedNow"))+")\n          ")]):_vm._e()]),(_vm.mainEditionDesc != '')?_c('div',[(_vm.mainEditionDesc != '')?_c('div',{staticClass:"title"},[_vm._v("\n            "+_vm._s(_vm.$t("myLicense.edition"))+":\n          ")]):_vm._e(),(_vm.mainEditionDesc != '')?_c('div',[_vm._v(_vm._s(_vm.mainEditionDesc))]):_vm._e(),_c('div',{staticClass:"seperator"}),_c('div',{staticClass:"title"},[_vm._v(_vm._s(_vm.$t("myLicense.start"))+":")]),_c('div',[_vm._v(_vm._s(_vm.periodStartStr))]),_c('div',{staticClass:"title"},[_vm._v(_vm._s(_vm.$t("myLicense.end"))+":")]),_c('div',[_vm._v(_vm._s(_vm.periodEndStr))]),(_vm.userType.ipUser())?_c('div',{staticClass:"stations-title"},[_vm._v("\n            "+_vm._s(`${_vm.$t("managePanel.maxStations")} ${_vm.otzarStations}`)+"\n          ")]):_vm._e()]):_c('div',[_vm._v("\n          "+_vm._s(_vm.$t("myLicense.noLic"))+"\n        ")])]),(!_vm.userType.ipUser() && _vm.tickets.length > 0)?_c('div',{staticClass:"contact-support flex-c",staticStyle:{"padding":"5px"}},[_c('div',{staticClass:"seperator"}),_c('div',{staticClass:"mrg-b-12 bold main-title"},[_vm._v("\n          "+_vm._s(_vm.tickets.length == 1
              ? _vm.$t("myLicense.youHaveViewTicket")
              : _vm.$t("myLicense.youHaveViewTickets"))+"\n        ")]),_vm._l((_vm.tickets),function(ticket){return _c('div',{key:ticket.id},[_c('div',{staticStyle:{"padding":"0px 20px 0px 20px"}},[_vm._v(_vm._s(ticket.info))]),_c('div',{staticStyle:{"padding":"5px","font-weight":"500"}},[_vm._v("\n            "+_vm._s(_vm.$t("myLicense.youHaveLeft"))+" "+_vm._s(ticket.daysLeft)+"\n            "+_vm._s(_vm.$t("general.outof"))+" "+_vm._s(ticket.days)+"\n          ")]),_c('div',{directives:[{name:"tooltip",rawName:"v-tooltip",value:(
              _vm.activatedTickets[ticket.id]
                ? { content: _vm.$t('myLicense.dayActualized') }
                : false
            ),expression:"\n              activatedTickets[ticket.id]\n                ? { content: $t('myLicense.dayActualized') }\n                : false\n            "}],staticClass:"btn btn-larg btn-center",class:{ disable: _vm.activatedTickets[ticket.id] },staticStyle:{"margin":"auto"},on:{"click":function($event){return _vm.doActualizeDay(ticket.id)}}},[_vm._v("\n            "+_vm._s(_vm.$t("myLicense.actualizeDay"))+"\n          ")]),_c('div',{staticClass:"seperator"})])})],2):_vm._e(),_c('div'),_c('div',{staticClass:"contact-support",staticStyle:{"padding-top":"20px"}},[_c('div',{staticClass:"seperator"}),_c('div',{staticClass:"mrg-b-6 bold main-title"},[_vm._v("\n          "+_vm._s(_vm.$t("myLicense.MEF_license"))+"\n          "),(_vm.mef && !this.hasMefConnection)?_c('div',{staticClass:"not-connected"},[_vm._v("\n            ("+_vm._s(_vm.$t("login.notConnectedNow"))+")\n          ")]):_vm._e()]),(!_vm.mef)?_c('div',[_vm._v("\n          "+_vm._s(_vm.$t("myLicense.noLic"))+"\n        ")]):_c('div',[_c('div',{staticClass:"title"},[_vm._v(_vm._s(_vm.$t("myLicense.start"))+":")]),_c('div',[_vm._v(_vm._s(_vm.formatDate(_vm.mef.periodStart)))]),_c('div',{staticClass:"title"},[_vm._v(_vm._s(_vm.$t("myLicense.end"))+":")]),_c('div',[_vm._v(_vm._s(_vm.formatDate(_vm.mef.periodEnd)))]),(_vm.userType.ipUser())?_c('div',{staticClass:"stations-title"},[_vm._v("\n            "+_vm._s(`${_vm.$t("managePanel.maxStations")} ${_vm.mefStations}`)+"\n          ")]):_vm._e()])]),(_vm.packages.size > 0)?_c('div',{staticClass:"contact-support",staticStyle:{"padding-top":"20px"}},[_c('div',{staticClass:"seperator"}),_c('div',{staticClass:"mrg-b-6 bold main-title"},[_vm._v("\n          "+_vm._s(_vm.$t("myLicense.packages"))+":\n        ")]),_vm._l((_vm.packages),function(p,index){return _c('div',{key:index},[_vm._v("\n          "+_vm._s(_vm.getPackageDesc(p))+"\n        ")])})],2):_vm._e(),(_vm.prints > 0)?_c('div',{staticClass:"contact-support"},[_c('div',{staticClass:"seperator"}),_c('div',{staticClass:"mrg-b-6 bold main-title"},[_vm._v("\n          "+_vm._s(_vm.$t("myLicense.printLicense"))+"\n        ")]),_c('div',{staticClass:"title"},[_vm._v(_vm._s(_vm.$t("myLicense.amount"))+":")]),_c('div',[_vm._v("\n          "+_vm._s(_vm.printsLeft)+" / "+_vm._s(_vm.prints)+" "+_vm._s(_vm.$t("myLicense.prints"))+"\n        ")])]):_vm._e()])]),_c('div',{staticClass:"ip-info"},[_vm._v("\n    "+_vm._s(_vm.IP)+"\n  ")])],1)
}
var staticRenderFns = []

export { render, staticRenderFns }