var render = function render(){var _vm=this,_c=_vm._self._c;return _c('div',{staticClass:"item extens-page-item",on:{"click":function($event){return _vm.goToPage(_vm.item)}}},[_c('div',{staticClass:"title"},[_vm._v(_vm._s(_vm.title)+" | "+_vm._s(_vm.crearedDate))]),_c('div',{staticClass:"content"},[(_vm.type == 'comment' && !_vm.edit)?_c('div',{ref:"comment",staticClass:"text"}):_vm._e(),(_vm.type == 'comment' && _vm.edit)?_c('textarea',{directives:[{name:"select",rawName:"v-select"}],ref:"comment",domProps:{"value":_vm.item.data},on:{"click":function($event){$event.stopPropagation();}}}):_vm._e(),(_vm.type == 'key')?_c('span',{staticClass:"label"},[_vm._v(_vm._s(_vm.$t("general.value")))]):_vm._e(),(_vm.type == 'key' && _vm.edit)?_c('textarea',{directives:[{name:"select",rawName:"v-select"}],staticClass:"text value",domProps:{"value":_vm.item.key},on:{"click":function($event){$event.stopPropagation();}}}):_vm._e(),(_vm.type == 'key' && !_vm.edit)?_c('div',{staticClass:"text"},[_vm._v(_vm._s(_vm.item.key))]):_vm._e(),(_vm.type == 'key')?_c('span',{staticClass:"label"},[_vm._v(_vm._s(_vm.$t("general.content")))]):_vm._e(),(_vm.type == 'key' && _vm.edit)?_c('textarea',{ref:"keyValue",staticClass:"text",domProps:{"value":_vm.item.value},on:{"click":function($event){$event.stopPropagation();}}}):_vm._e(),(_vm.type == 'key' && !_vm.edit)?_c('div',{ref:"key",staticClass:"text"},[_vm._v("\n      "+_vm._s(_vm.item.value)+"\n    ")]):_vm._e(),(_vm.type == 'link')?_c('div',[_c('span',{staticClass:"label"},[_vm._v(_vm._s(_vm.$t("files1.place"))+":")]),_c('div',{staticClass:"text"},[_vm._v("\n        "+_vm._s(_vm.item.bookId == _vm.item.linkedTo.bookId
            ? ""
            : _vm.getBookName(_vm.item.linkedTo.bookId))+"\n        | "+_vm._s(_vm.$t("general.page"))+"\n        "+_vm._s(_vm.item.linkedTo.letter)+"\n      ")]),(_vm.item.linkedTo.note)?_c('div',[_c('span',{staticClass:"label"},[_vm._v(_vm._s(_vm.$t("general.desc")))]),_c('div',{staticClass:"text"},[_vm._v("\n          "+_vm._s(_vm.item.linkedTo.note)+"\n        ")])]):_vm._e()]):_vm._e(),(_vm.type == 'marker')?_c('div',{staticClass:"image"},[_c('canvas',{ref:"canvas"})]):_vm._e()]),_c('div',{staticClass:"flex icons"},[(_vm.type != 'marker' && !_vm.edit)?_c('baseIcon',{staticClass:"icon-extens icon-garbage-extens icon-edit-extens",attrs:{"nameIcon":"edit-extens","width":"15","height":"15","pathIcon":"icons-ganeral"},on:{"click":function($event){$event.stopPropagation();return _vm.editMode(_vm.item)}}}):_vm._e(),(!_vm.edit)?_c('baseIcon',{staticClass:"icon-extens icon-garbage-extens",attrs:{"nameIcon":"icon-garbage-stroke","width":"15","height":"17","pathIcon":"icons-ganeral"},on:{"click":function($event){$event.stopPropagation();return _vm.remove(_vm.item)}}}):_vm._e(),(_vm.type == 'link')?_c('baseIcon',{staticClass:"icon-extens icon-link-extens icon-edit-extens",attrs:{"nameIcon":"link","width":"15","height":"15","pathIcon":"general"},on:{"click":function($event){$event.stopPropagation();return _vm.goToPage(_vm.item.linkedTo)}}}):_vm._e()],1),(_vm.edit)?_c('div',{staticClass:"edit-mode icon-extens icon-garbage-extens otz-icon cancel",on:{"click":_vm.cancelMode}},[_vm._v("\n    F\n  ")]):_vm._e(),(_vm.edit)?_c('div',{staticClass:"edit-mode icon-extens icon-garbage-extens otz-icon",on:{"click":function($event){return _vm.editMode(_vm.item.id)}}},[_vm._v("\n    A\n  ")]):_vm._e(),(_vm.showEditor)?_c('BaseCleanPopup',{directives:[{name:"body",rawName:"v-body"},{name:"zindex",rawName:"v-zindex"}],attrs:{"h":37,"winh":_vm.hUserExtens,"winw":_vm.wUserExtens,"noneOverlay":true},on:{"close":_vm.closeAllExtens},scopedSlots:_vm._u([{key:"header",fn:function(){return [_c('div',{staticClass:"flex-center-vh"},[_vm._v("\n        "+_vm._s(_vm.type == "comment"
            ? _vm.$t("comments.comment")
            : _vm.type == "link"
            ? _vm.$t("links.link")
            : _vm.$t("keys.key"))+"\n      ")])]},proxy:true}],null,false,677680088)},[(_vm.type == 'comment')?_c('add-user-exten',{attrs:{"tabId":_vm.tabId,"note":_vm.editorItem,"book":_vm.getCurrentBook},on:{"close":function($event){_vm.showEditor = false}}}):(_vm.type == 'key')?_c('add-user-key',{attrs:{"tabId":_vm.tabId,"item":_vm.editorItem,"book":_vm.getCurrentBook},on:{"close":function($event){_vm.showEditor = false}}}):(_vm.type == 'link')?_c('add-user-link',{attrs:{"tabId":_vm.tabId,"item":_vm.editorItem,"edit":true,"book":_vm.getCurrentBook},on:{"close":_vm.closeAllExtens,"gotoitempage":(item) => _vm.$emit('click', item)}}):_vm._e()],1):_vm._e()],1)
}
var staticRenderFns = []

export { render, staticRenderFns }