var render = function render(){var _vm=this,_c=_vm._self._c;return _c('div',{staticClass:"rtl pages-navigator"},[_c('div',{directives:[{name:"tooltip",rawName:"v-tooltip",value:({ content: this.$t('tooltip.firstPage'), placement: 'right' }),expression:"{ content: this.$t('tooltip.firstPage'), placement: 'right' }"}],staticClass:"arrow-icon otz-icon",class:{ disable: _vm.isFirstPage },on:{"click":function($event){$event.stopPropagation();return _vm.setPage(0)},"dblclick":function($event){$event.stopPropagation();}}},[_vm._v("\n    6\n  ")]),_c('div',{directives:[{name:"tooltip",rawName:"v-tooltip",value:({
      content: this.$t('tooltip.prevPage10'),
      placement: 'right',
    }),expression:"{\n      content: this.$t('tooltip.prevPage10'),\n      placement: 'right',\n    }"}],staticClass:"arrow-icon otz-icon",class:{ disable: _vm.isFirstPage },on:{"click":function($event){$event.stopPropagation();return _vm.incPage(-10)},"dblclick":function($event){$event.stopPropagation();}}},[_vm._v("\n    5\n  ")]),_c('div',{directives:[{name:"tooltip",rawName:"v-tooltip",value:({ content: this.$t('tooltip.prevPage1'), placement: 'right' }),expression:"{ content: this.$t('tooltip.prevPage1'), placement: 'right' }"}],staticClass:"arrow-icon otz-icon",class:{ disable: _vm.isFirstPage },on:{"click":function($event){$event.stopPropagation();return _vm.incPage(-1)},"dblclick":function($event){$event.stopPropagation();}}},[_vm._v("\n    7\n  ")]),_c('input',{domProps:{"value":_vm.page},on:{"keydown":function($event){if(!$event.type.indexOf('key')&&_vm._k($event.keyCode,"enter",13,$event.key,"Enter"))return null;return _vm.goToPage.apply(null, arguments)},"wheel":_vm.wheeling,"focus":function($event){return _vm.selectText($event.target)}}}),_c('span',{staticClass:"text"},[_vm._v(_vm._s(_vm.$t("book.outof")))]),_c('span',[_vm._v(" ")]),_c('span',{staticClass:"text"},[_vm._v(_vm._s(_vm.numPages))]),_c('div',{directives:[{name:"tooltip",rawName:"v-tooltip",value:({ content: this.$t('tooltip.nextPage1'), placement: 'right' }),expression:"{ content: this.$t('tooltip.nextPage1'), placement: 'right' }"}],staticClass:"arrow-icon otz-icon",class:{ disable: _vm.isLastPage },on:{"click":function($event){$event.stopPropagation();return _vm.incPage(1)},"dblclick":function($event){$event.stopPropagation();}}},[_vm._v("\n    2\n  ")]),_c('div',{directives:[{name:"tooltip",rawName:"v-tooltip",value:({
      content: this.$t('tooltip.nextPage10'),
      placement: 'right',
    }),expression:"{\n      content: this.$t('tooltip.nextPage10'),\n      placement: 'right',\n    }"}],staticClass:"arrow-icon otz-icon",class:{ disable: _vm.isLastPage },on:{"click":function($event){$event.stopPropagation();return _vm.incPage(10)},"dblclick":function($event){$event.stopPropagation();}}},[_vm._v("\n    4\n  ")]),_c('div',{directives:[{name:"tooltip",rawName:"v-tooltip",value:({ content: this.$t('tooltip.lastPage'), placement: 'right' }),expression:"{ content: this.$t('tooltip.lastPage'), placement: 'right' }"}],staticClass:"arrow-icon otz-icon",class:{ disable: _vm.isLastPage },on:{"click":function($event){$event.stopPropagation();return _vm.setPage(_vm.numPages)},"dblclick":function($event){$event.stopPropagation();}}},[_vm._v("\n    3\n  ")])])
}
var staticRenderFns = []

export { render, staticRenderFns }